-- Team-level daily reports, generated by team leaders
CREATE TABLE team_reports (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    team_id         UUID NOT NULL REFERENCES teams(id),
    leader_id       BIGINT NOT NULL REFERENCES users(id),
    report_date     DATE NOT NULL,
    content         TEXT NOT NULL,
    feishu_doc_url  TEXT,
    member_report_ids UUID[] NOT NULL DEFAULT '{}',
    session_ids     UUID[] NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (team_id, report_date)
);

CREATE INDEX idx_team_reports_team_date ON team_reports(team_id, report_date DESC);
